GRAPHQL http://localhost:1337/graphql



 query {
artisans{
    name,
    location,
    categories{name},
    image{
      name,
      url,
    },
  },
  categories{
    name,
    image{
      name,
      url,
    },
  },


}
###
